export type JourneyEvent = {
  time: string;
  zone: string;
  action: string;
  difficulty: boolean;
  difficultyNote?: string;
};

export type Passenger = {
  id: string;
  name: string;
  age: number;
  nationality: string;
  flightNumber: string;
  destination: string;
  boardingGate: string;
  boardingTime: string;
  status: "navigating" | "shopping" | "waiting" | "difficulty" | "boarded";
  avatar: string;
  shirtColor: string;
  journeyStart: string;
  currentZone: string;
  eta: string;
  journeyLog: JourneyEvent[];
  pathIndex: number;
  pathPoints: [number, number][];
  purchases: { item: string; price: number }[];
  needsHelp: boolean;
  language: string;
  // Runtime fields
  position: [number, number];
  trail: [number, number][];
  tickCount: number;
};

export const passengersData: Passenger[] = [
  {
    id: "PAX-001",
    name: "Amara Osei",
    age: 34,
    nationality: "Ghanaian",
    flightNumber: "EK-427",
    destination: "Dubai",
    boardingGate: "Gate C1",
    boardingTime: "11:45 AM",
    status: "navigating",
    avatar: "\u{1F9D1}",
    shirtColor: "#E84A4A",
    journeyStart: "09:00 AM",
    currentZone: "Main Corridor",
    eta: "12 mins to gate",
    journeyLog: [
      { time: "09:00 AM", zone: "Security", action: "Passed security check", difficulty: false },
      { time: "09:12 AM", zone: "Main Corridor", action: "Walking toward gates", difficulty: false },
      { time: "09:18 AM", zone: "Info Desk", action: "Asked for gate directions", difficulty: false },
      { time: "09:24 AM", zone: "Main Corridor", action: "Heading to Gate C1", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [-280, 0], [-240, 0], [-200, 0], [-160, 0], [-120, 0], [-80, 0],
      [-40, 0], [0, 0], [40, 0], [80, 0], [120, 0], [120, -40], [120, -80],
    ],
    purchases: [],
    needsHelp: false,
    language: "English",
    position: [-280, 0],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-002",
    name: "Yuki Tanaka",
    age: 28,
    nationality: "Japanese",
    flightNumber: "NH-209",
    destination: "Tokyo",
    boardingGate: "Gate A2",
    boardingTime: "12:30 PM",
    status: "shopping",
    avatar: "\u{1F468}",
    shirtColor: "#4A90D9",
    journeyStart: "09:15 AM",
    currentZone: "Sky Cafe",
    eta: "45 mins to gate",
    journeyLog: [
      { time: "09:15 AM", zone: "Security", action: "Cleared security", difficulty: false },
      { time: "09:30 AM", zone: "Main Corridor", action: "Walking to shops", difficulty: false },
      { time: "09:40 AM", zone: "Duty Free", action: "Browsing electronics", difficulty: false },
      { time: "09:55 AM", zone: "Sky Cafe", action: "Ordered matcha latte $5.50", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [-280, 0], [-240, 0], [-200, 0], [-180, 0], [-180, 20], [-180, 40], [-180, 60],
      [-140, 60], [-100, 60], [-60, 60], [-60, 40], [-60, 20], [-60, 0],
      [-40, 0], [-80, 0], [-120, 0], [-120, -40], [-120, -80],
    ],
    purchases: [
      { item: "Matcha Latte", price: 5.50 },
      { item: "USB-C Cable", price: 12.99 },
    ],
    needsHelp: false,
    language: "Japanese",
    position: [-180, 60],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-003",
    name: "Maria Santos",
    age: 72,
    nationality: "Brazilian",
    flightNumber: "LA-801",
    destination: "Sao Paulo",
    boardingGate: "Gate B1",
    boardingTime: "11:15 AM",
    status: "navigating",
    avatar: "\u{1F475}",
    shirtColor: "#9B59B6",
    journeyStart: "08:30 AM",
    currentZone: "Main Corridor",
    eta: "22 mins to gate",
    journeyLog: [
      { time: "08:30 AM", zone: "Immigration", action: "Cleared immigration", difficulty: false },
      { time: "08:50 AM", zone: "Main Corridor", action: "Slow walk, using cane", difficulty: false },
      { time: "09:10 AM", zone: "Restrooms West", action: "Rest break", difficulty: false },
      { time: "09:25 AM", zone: "Main Corridor", action: "Resumed walking to gate", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [280, 0], [240, 0], [200, 0], [160, 0], [120, 0], [80, 0],
      [40, 0], [0, 0], [-40, 0], [-40, -40], [-40, -80],
    ],
    purchases: [],
    needsHelp: false,
    language: "Portuguese",
    position: [280, 0],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-004",
    name: "Ahmed Al-Rashid",
    age: 41,
    nationality: "Saudi",
    flightNumber: "SV-302",
    destination: "Riyadh",
    boardingGate: "Gate C2",
    boardingTime: "12:00 PM",
    status: "difficulty",
    avatar: "\u{1F468}\u{200D}\u{2764}\u{FE0F}\u{200D}\u{1F468}",
    shirtColor: "#E67E22",
    journeyStart: "09:00 AM",
    currentZone: "Restrooms West",
    eta: "Unknown",
    journeyLog: [
      { time: "09:00 AM", zone: "Security", action: "Passed security", difficulty: false },
      { time: "09:15 AM", zone: "Main Corridor", action: "Walking to gate area", difficulty: false },
      { time: "09:22 AM", zone: "Restrooms West", action: "Looking for washroom", difficulty: true, difficultyNote: "Searched for washroom 4 mins, approached staff" },
      { time: "09:28 AM", zone: "Restrooms West", action: "Still confused by signage", difficulty: true, difficultyNote: "Signage unclear, asked two staff members" },
    ],
    pathIndex: 0,
    pathPoints: [
      [-280, 0], [-240, 0], [-200, 0], [-200, 10], [-220, 10], [-220, 0],
      [-200, 0], [-220, 10], [-220, 0], [-200, 0], [-160, 0], [-120, 0],
      [-80, 0], [0, 0], [80, 0], [120, 0], [120, -40], [120, -80],
    ],
    purchases: [],
    needsHelp: true,
    language: "Arabic",
    position: [-220, 10],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-005",
    name: "Priya Sharma",
    age: 26,
    nationality: "Indian",
    flightNumber: "AI-131",
    destination: "Mumbai",
    boardingGate: "Gate A1",
    boardingTime: "11:30 AM",
    status: "shopping",
    avatar: "\u{1F469}",
    shirtColor: "#2ECC71",
    journeyStart: "09:05 AM",
    currentZone: "Duty Free",
    eta: "35 mins to gate",
    journeyLog: [
      { time: "09:05 AM", zone: "Security", action: "Cleared security", difficulty: false },
      { time: "09:20 AM", zone: "Duty Free", action: "Browsing perfumes", difficulty: false },
      { time: "09:35 AM", zone: "Duty Free", action: "Purchased perfume $48.00", difficulty: false },
      { time: "09:45 AM", zone: "Bookstore", action: "Looking for novels", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [-280, 0], [-240, 0], [-200, 0], [-160, 0], [-100, 0], [-60, 0],
      [-60, 20], [-60, 40], [-60, 60], [-20, 60], [20, 60], [60, 60],
      [100, 60], [140, 60], [180, 60], [180, 40], [180, 20], [180, 0],
      [160, 0], [120, 0], [80, 0], [40, 0], [0, 0], [-40, 0], [-80, 0],
      [-120, 0], [-160, 0], [-200, 0], [-200, -40], [-200, -80],
    ],
    purchases: [
      { item: "Chanel No. 5", price: 48.00 },
      { item: "Novel - Kite Runner", price: 14.99 },
    ],
    needsHelp: false,
    language: "Hindi",
    position: [-60, 60],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-006",
    name: "Chen Wei",
    age: 55,
    nationality: "Chinese",
    flightNumber: "CA-981",
    destination: "Beijing",
    boardingGate: "Gate B2",
    boardingTime: "11:50 AM",
    status: "waiting",
    avatar: "\u{1F468}\u{200D}\u{1F468}",
    shirtColor: "#3498DB",
    journeyStart: "08:45 AM",
    currentZone: "Gate B2",
    eta: "Already at gate",
    journeyLog: [
      { time: "08:45 AM", zone: "Immigration", action: "Cleared immigration", difficulty: false },
      { time: "09:00 AM", zone: "Pharmacy", action: "Bought medicine $22.00", difficulty: false },
      { time: "09:20 AM", zone: "Main Corridor", action: "Walked to gate area", difficulty: false },
      { time: "09:35 AM", zone: "Gate B2", action: "Seated, waiting for boarding", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [280, 0], [240, 0], [200, 0], [160, 0], [120, 0], [80, 60],
      [80, 40], [80, 20], [80, 0], [40, 0], [40, -40], [40, -80],
    ],
    purchases: [
      { item: "Cold Medicine", price: 22.00 },
    ],
    needsHelp: false,
    language: "Mandarin",
    position: [40, -80],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-007",
    name: "Olga Petrova",
    age: 38,
    nationality: "Russian",
    flightNumber: "SU-257",
    destination: "Moscow",
    boardingGate: "Gate C1",
    boardingTime: "11:45 AM",
    status: "navigating",
    avatar: "\u{1F478}",
    shirtColor: "#1ABC9C",
    journeyStart: "09:10 AM",
    currentZone: "Main Corridor",
    eta: "18 mins to gate",
    journeyLog: [
      { time: "09:10 AM", zone: "Security", action: "Security check complete", difficulty: false },
      { time: "09:22 AM", zone: "Bookstore", action: "Bought magazine $8.50", difficulty: false },
      { time: "09:32 AM", zone: "Main Corridor", action: "Walking toward C gates", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [-280, 0], [-240, 0], [-200, 0], [-160, 0], [-120, 0], [-80, 0],
      [-40, 0], [0, 0], [40, 0], [80, 0], [120, 0], [120, -40], [120, -80],
    ],
    purchases: [
      { item: "Travel Magazine", price: 8.50 },
    ],
    needsHelp: false,
    language: "Russian",
    position: [-160, 0],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-008",
    name: "James Okafor",
    age: 29,
    nationality: "Nigerian",
    flightNumber: "ET-702",
    destination: "Lagos",
    boardingGate: "Gate A2",
    boardingTime: "12:30 PM",
    status: "navigating",
    avatar: "\u{1F466}",
    shirtColor: "#F39C12",
    journeyStart: "09:20 AM",
    currentZone: "Main Corridor",
    eta: "28 mins to gate",
    journeyLog: [
      { time: "09:20 AM", zone: "Security", action: "Passed security", difficulty: false },
      { time: "09:30 AM", zone: "Info Desk", action: "Checked flight info", difficulty: false },
      { time: "09:38 AM", zone: "Main Corridor", action: "Walking to A gates", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [-280, 0], [-240, 0], [-200, 0], [-160, 0], [-120, 0], [-80, 0],
      [-40, 0], [0, 0], [0, 20], [0, 0], [-40, 0], [-80, 0], [-120, 0],
      [-120, -40], [-120, -80],
    ],
    purchases: [],
    needsHelp: false,
    language: "English",
    position: [-240, 0],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-009",
    name: "Sophie Dubois",
    age: 45,
    nationality: "French",
    flightNumber: "AF-226",
    destination: "Paris",
    boardingGate: "Gate B1",
    boardingTime: "11:15 AM",
    status: "boarded",
    avatar: "\u{1F469}\u{200D}\u{1F469}",
    shirtColor: "#8E44AD",
    journeyStart: "08:00 AM",
    currentZone: "Gate B1",
    eta: "Boarded",
    journeyLog: [
      { time: "08:00 AM", zone: "Security", action: "Early arrival, cleared security", difficulty: false },
      { time: "08:15 AM", zone: "Sky Cafe", action: "Breakfast croissant $7.50", difficulty: false },
      { time: "08:40 AM", zone: "Duty Free", action: "Bought chocolates $18.00", difficulty: false },
      { time: "09:00 AM", zone: "Gate B1", action: "Boarded flight", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [-280, 0], [-240, 0], [-200, 0], [-180, 0], [-180, 60], [-140, 60],
      [-100, 60], [-60, 60], [-60, 40], [-60, 20], [-60, 0], [-40, 0],
      [-40, -40], [-40, -80],
    ],
    purchases: [
      { item: "Croissant & Coffee", price: 7.50 },
      { item: "Lindt Chocolates", price: 18.00 },
    ],
    needsHelp: false,
    language: "French",
    position: [-40, -80],
    trail: [],
    tickCount: 0,
  },
  {
    id: "PAX-010",
    name: "Raj Patel",
    age: 31,
    nationality: "Indian",
    flightNumber: "EK-512",
    destination: "Delhi",
    boardingGate: "Gate C2",
    boardingTime: "12:00 PM",
    status: "navigating",
    avatar: "\u{1F468}\u{200D}\u{1F4BC}",
    shirtColor: "#E74C3C",
    journeyStart: "09:25 AM",
    currentZone: "Main Corridor",
    eta: "20 mins to gate",
    journeyLog: [
      { time: "09:25 AM", zone: "Security", action: "Rushed through security", difficulty: false },
      { time: "09:32 AM", zone: "Pharmacy", action: "Quick stop for water $2.00", difficulty: false },
      { time: "09:38 AM", zone: "Main Corridor", action: "Speed walking to gate", difficulty: false },
    ],
    pathIndex: 0,
    pathPoints: [
      [-280, 0], [-240, 0], [-200, 0], [-160, 0], [-120, 0], [80, 0],
      [80, 20], [80, 0], [40, 0], [0, 0], [40, 0], [80, 0], [120, 0],
      [120, -40], [120, -80],
    ],
    purchases: [
      { item: "Bottled Water", price: 2.00 },
    ],
    needsHelp: false,
    language: "Hindi",
    position: [-120, 0],
    trail: [],
    tickCount: 0,
  },
];
